# Generated by Django 4.0.1 on 2022-10-08 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cyclone_info',
            name='link',
        ),
        migrations.RemoveField(
            model_name='cyclone_info',
            name='published',
        ),
        migrations.AddField(
            model_name='cyclone_info',
            name='area',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cyclone_info',
            name='image',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
    ]
